version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: uv
    allow:
      - dependency-type: all
    directory: /
    schedule:
      interval: daily
