services:
  cleanup:
    entrypoint:
      - /bin/rm
      - -fr
      - dist
      - html
      - src/python_rainwave_client.egg-info
    image: ghcr.io/williamjacksn/python-rainwave-client-helper
    init: true
    volumes:
      - ./:/home/python/python-rainwave-client
    working_dir: /home/python/python-rainwave-client

  docs-build:
    entrypoint:
      - /home/python/venv/bin/sphinx-build
      - docs
      - html
    image: ghcr.io/williamjacksn/python-rainwave-client-helper
    init: true
    volumes:
      - ./:/home/python/python-rainwave-client
    working_dir: /home/python/python-rainwave-client

  pip-compile:
    entrypoint:
      - /home/python/venv/bin/pip-compile
    image: ghcr.io/williamjacksn/pip-tools:py3.13
    init: true
    volumes:
      - ./:/home/python/python-rainwave-client
    working_dir: /home/python/python-rainwave-client

  py-build:
    entrypoint:
      - /home/python/venv/bin/python
      - -m
      - build
    image: ghcr.io/williamjacksn/python-rainwave-client-helper
    init: true
    volumes:
      - ./:/home/python/python-rainwave-client
    working_dir: /home/python/python-rainwave-client

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/python-rainwave-client-helper
    init: true
    volumes:
      - ./:/home/python/python-rainwave-client
    working_dir: /home/python/python-rainwave-client

  tests:
    entrypoint:
      - python
      - tests.py
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      RW_KEY:
      RW_USER_ID:
    image: python:3.9-slim
    init: true
    volumes:
      - ./:/home/python/python-rainwave-client
    working_dir: /home/python/python-rainwave-client
