name: Build the container image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:

  build:
    name: Build the container image
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repository
        uses: actions/checkout@v2.3.5

      - name: Build the container image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: python-rainwave-client-helper

      - name: Tag and push the image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ${{ github.repository_owner }}/python-rainwave-client-helper
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          tag_with_ref: true
          add_git_labels: true
